#!/bin/bash
set -euxo pipefail
VNC_PASSWORD=instruqt
VNC_USER=instruqt

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

# Install tightvncserver, xfce4 desktop and certbot
apt -y update
DEBIAN_FRONTEND=noninteractive apt -y install ubuntu-desktop kde-plasma-desktop ubuntu-mate-core xubuntu-core lightdm
systemctl start lightdm.service
service lightdm start
