#!/bin/bash

set -xo pipefail

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

mkdir /root/workspace
cd /root/workspace
set-workdir /root/workspace