version: "3"
containers:
- name: container
  image: ubuntu
  shell: /bin/bash
  memory: 256
- name: grafana
  image: grafana/grafana-enterprise
  ports:
  - 3000
  memory: 256
- name: osdashboard
  image: opensearchproject/opensearch-dashboards
  ports:
  - 9200
  memory: 256
